### ISSUE TITLE
ModuleNotFoundError: No module named 'maad'

### ISSUE THREAD

**Issue by QinCaii** [IceKyrin/sovits_f0_infer#13]
>> flask_api.py
Traceback (most recent call last):
  File ".\flask_api.py", line 10, in <module>
    from sovits.infer_tool import Svc, RealTimeVC, SvcONNXInferModel
  File ".\sovits\infer_tool.py", line 6, in <module>
    import maad
ModuleNotFoundError: No module named 'maad'

require已经装好了的，安装txt没有报错，我忽略了什么吗?

**Comment by IceKyrin** [comment]
pip install scikit-maad，这个maad库

**Comment by QinCaii** [comment]
librosa和onnxruntime也是手动装的
