### ISSUE TITLE
DAW VST support

### ISSUE THREAD

**Issue by zhaohui8969** [IceKyrin/sovits_f0_infer#8]
我写了一个VST插件，基于HTTP异步IO，可以直接和这个模型对接。VST插件可以和DAW结合，便于直播

**Comment by zhaohui8969** [comment]
https://github.com/zhaohui8969/VST_NetProcess

**Comment by IceKyrin** [comment]
我肝不动了，要啥api可以给你写一下，c++应该能调用python吧，或者做成本地的http服务端也行，你给个需求文档

**Comment by IceKyrin** [comment]
http_server文件加了，其实很简单，就一个加载模型，一个上传文件获取返回音频，http_cli有示例。模型和json可以去hug下载xxx_epochs.pth（音源）hubert.pt（前置处理）

**Comment by zhaohui8969** [comment]
OK，我在写VST插件的时候，用Flask将模型封装成HTTP接口，已经在studio One里面测试可用了

**Comment by IceKyrin** [comment]
话说有没有打包好的vst，我改api接你那个也行，我这没装vscode

**Comment by zhaohui8969** [comment]
https://github.com/zhaohui8969/VST_NetProcess-/releases/tag/v1.0

**Comment by IceKyrin** [comment]
_(:D)∠)_改host之后接上了，但是好像是api返回格式没匹配好，有空能不能给个flask的参考，我照着一改。emmm接口打包成127.0.0.1可能方便一点

**Comment by zhaohui8969** [comment]
这里有个基于docker封装的直接可用的Flask后端，https://github.com/zhaohui8969/ai_voice_change_server

**Comment by IceKyrin** [comment]
优秀
